In [1]:
# importing packages
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
# loading the data
df = pd.read_csv("C://Users//Admin//Documents//Coding DOCS//CampusX Data Science//Datasets//IPL_deliveries.csv")

# EDA on IPL Deliveries:

## 1. Understanding the Data :

In [3]:
df.head()

match_id  inning           batting_team                 bowling_team  over  \
0    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
1    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
2    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
3    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
4    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   

   ball       batter   bowler  non_striker  batsman_runs  extra_runs  \
0     1   SC Ganguly  P Kumar  BB McCullum             0           1   
1     2  BB McCullum  P Kumar   SC Ganguly             0           0   
2     3  BB McCullum  P Kumar   SC Ganguly             0           1   
3     4  BB McCullum  P Kumar   SC Ganguly             0           0   
4     5  BB McCullum  P Kumar   SC Ganguly             0           0   

   total_runs extras_type  is_wicket player_dismissed dismissal_kind fielder  
0           1     legbyes          0              NaN            NaN     NaN  
1           0         NaN          0              NaN            NaN     NaN  
2           1       wides          0              NaN            NaN     NaN  
3           0         NaN          0              NaN            NaN     NaN  
4           0         NaN          0              NaN            NaN     NaN

In [4]:
# how big is the data ?
df.shape

(260920, 17)

In [5]:
# missing values 
df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [6]:
# duplicate rows
df.duplicated().sum()

0

## 2. Univariate Analysis:

In [7]:
df.head()

match_id  inning           batting_team                 bowling_team  over  \
0    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
1    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
2    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
3    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   
4    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0   

   ball       batter   bowler  non_striker  batsman_runs  extra_runs  \
0     1   SC Ganguly  P Kumar  BB McCullum             0           1   
1     2  BB McCullum  P Kumar   SC Ganguly             0           0   
2     3  BB McCullum  P Kumar   SC Ganguly             0           1   
3     4  BB McCullum  P Kumar   SC Ganguly             0           0   
4     5  BB McCullum  P Kumar   SC Ganguly             0           0   

   total_runs extras_type  is_wicket player_dismissed dismissal_kind fielder  
0           1     legbyes          0              NaN            NaN     NaN  
1           0         NaN          0              NaN            NaN     NaN  
2           1       wides          0              NaN            NaN     NaN  
3           0         NaN          0              NaN            NaN     NaN  
4           0         NaN          0              NaN            NaN     NaN

In [8]:
df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

### a. match_id:

In [9]:
# We can refer to the IPL Matches Dataset for the match details using match_id
print(f'No. of Matches: {len(df.match_id.unique())}') 

No. of Matches: 1095


### b. inning:

In [10]:
df.inning.unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [11]:
df.inning.value_counts()

inning
1    135018
2    125741
3        77
4        72
5         8
6         4
Name: count, dtype: int64

### c. over and ball:

In [12]:
df.over.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [13]:
df.ball.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [14]:
df.ball.value_counts()

ball
1     42210
2     42106
3     42002
4     41891
5     41752
6     41619
7      7776
8      1307
9       225
10       30
11        2
Name: count, dtype: int64

### d. Batsman_runs:

In [15]:
df.batsman_runs.unique()

array([0, 4, 6, 1, 2, 5, 3], dtype=int64)

### e. Extra_runs and Extra_types:

In [16]:
df.extra_runs.unique()

array([1, 0, 5, 4, 2, 3, 7], dtype=int64)

In [17]:
df.extras_type.unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

### f. is_wicket:

In [18]:
df.is_wicket.unique()

array([0, 1], dtype=int64)

### g. player_dismissed and dismissal_kind:

In [19]:
df[df.dismissal_kind=='obstructing the field']

match_id  inning           batting_team         bowling_team  over  \
91751     598061       2  Kolkata Knight Riders        Pune Warriors    17   
178570   1181766       2         Delhi Capitals  Sunrisers Hyderabad    19   
258526   1426299       2    Chennai Super Kings     Rajasthan Royals    15   

        ball     batter      bowler non_striker  batsman_runs  extra_runs  \
91751      5  YK Pathan  WD Parnell      DB Das             0           0   
178570     5   A Mishra    KK Ahmed    KMA Paul             0           0   
258526     5  RA Jadeja  Avesh Khan  RD Gaikwad             1           0   

        total_runs extras_type  is_wicket player_dismissed  \
91751            0         NaN          1        YK Pathan   
178570           0         NaN          1         A Mishra   
258526           1         NaN          1        RA Jadeja   

               dismissal_kind fielder  
91751   obstructing the field     NaN  
178570  obstructing the field     NaN  
258526  obstructing the field     NaN

In [20]:
df.dismissal_kind.unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [21]:
df.dismissal_kind.value_counts()

dismissal_kind
caught                   8063
bowled                   2212
run out                  1114
lbw                       800
caught and bowled         367
stumped                   358
retired hurt               15
hit wicket                 15
obstructing the field       3
retired out                 3
Name: count, dtype: int64

### h. Fielder:

In [22]:
df.fielder.value_counts()

fielder
MS Dhoni            220
KD Karthik          199
AB de Villiers      141
RV Uthappa          133
WP Saha             131
                   ... 
TS Mills              1
Ankit Soni            1
WPUJC Vaas            1
B Laughlin            1
T Kohler-Cadmore      1
Name: count, Length: 607, dtype: int64

## Matches Analysis with Deliveries:

In [29]:
# DD batting
df[df.match_id==419134][df[df.match_id==419134].inning==1].total_runs.sum()

188

In [30]:
# RR batting
df[df.match_id==419134][df[df.match_id==419134].inning==2].total_runs.sum()

121